### ISSUE TITLE
Unhandled Exception: PlatformException(MediaInfo, TracksUnreadable, null)

### ISSUE THREAD

**Issue by DebugTheCode** [ened/flutter_plugin_media_info#10]
Same as #9 

But this also on iOS device.

Trying to read media info from a .mp3 file (audio)

**Comment by ened** [comment]
Hi, have you tried with v0.6.2 ?

**Comment by DebugTheCode** [comment]
@ened Yes.

**Comment by ened** [comment]
Is it possible to attach the Mp3 file here for reference? It will be included in the projects e2e tests.

**Comment by DebugTheCode** [comment]
The files from [https://www.bensound.com/](url) -> Summer & Ukele

**Comment by yy1300326388** [comment]
[ambient_c_motion.mp3.zip](https://github.com/ened/flutter_plugin_media_info/files/4953271/ambient_c_motion.mp3.zip)
First of all, thank you very much. I also encountered the same problem. The mp3 file cannot be obtained. On the iOS simulator, I uploaded the zip on github. You can unzip it.
