### ISSUE TITLE
Execution failed for task ':app:minifyReleaseWithR8'.

### ISSUE THREAD

**Issue by venliong** [ened/flutter_plugin_media_info#22]
Flutter App that with both media_info and video_player, failed to minify when build release version APK.

**Comment by ened** [comment]
@venliong which version of both plugins did you use. Can you please submit a example project on Github?

**Comment by venliong** [comment]
There's no problem about media_info, after a lot of trying I find out it's [another](https://pub.dev/packages/tobias) plugin's problem. Sorry for the issue without fully testing.
