### ISSUE TITLE
Build apk error

### ISSUE THREAD

**Issue by mosluce** [ened/flutter_plugin_media_info#28]
macOS 12.5.1
Flutter 3.0.5
Android Studio Android Studio Chipmunk | 2021.2.1 Patch 2

Execution failed for task ':media_info:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/mosluce/.gradle/caches/transforms-3/5e083c06c9925c2309f02468fc66e376/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by kjawadDeveloper2** [comment]
@ened i am also facing this error.

**Comment by tarek360** [comment]
it works fine when building a release appbundle, but I don't know why it fails when building a release apk: "failed for task ':media_info:verifyReleaseResources'."



- `flutter build appbundle --release` works  ✅
- `flutter build apk --release` is failing ❌

**Comment by ened** [comment]
This works fine in the example app - it looks like a problem with your local AndroidX dependency setup https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found
