### ISSUE TITLE
Unhandled Exception: PlatformException(MediaInfo, TracksUnreadable, null)

### ISSUE THREAD

**Issue by dmcrobin** [ened/flutter_plugin_media_info#9]
I am trying to get media info using :
`final Map<String, dynamic> mediaInfo = await _mediaInfo.getMediaInfo(file);`
But throwing this error:

`/ExoPlayerImpl( 4597): Init c82143f [ExoPlayerLib/2.10.5] [violet, Redmi Note 7 Pro, Xiaomi, 28]`
`W/WavHeaderReader( 4597): Ignoring unknown WAV chunk: 1279873876`
`I/ExoPlayerImpl( 4597): Release c82143f [ExoPlayerLib/2.10.5] [violet, Redmi Note 7 Pro, Xiaomi, 28] [goog.exo.core]`
`E/flutter ( 4597): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(MediaInfo, TracksUnreadable, null)`

**Comment by ened** [comment]
Can you share the file? The TracksUnreadable error indicates it may be a unsupported format.

**Comment by dmcrobin** [comment]
What the media file??

**Comment by ened** [comment]
Yeah, please share the media file. Else I can not really help..

Can the media file be played in any other player on your phone?

**Comment by dmcrobin** [comment]
It is daddy yankee - con calma song, and it is playing on my device. I've attached the media file in zip.
What exactly is the error?? Could define more.
[Daddy_Yankee_&_Snow_-_Con_Calma_(Video_Oficial)(256k).zip](https://github.com/ened/flutter_plugin_media_info/files/4642332/Daddy_Yankee_._Snow_-_Con_Calma_.Video_Oficial.256k.zip)

**Comment by dmcrobin** [comment]
Any Updates??

**Comment by dmcrobin** [comment]
Hey @ened ... What's the error???

**Comment by Tonigt** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(MediaInfo, com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream., null)
E/flutter (13899): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (13899): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (13899): <asynchronous suspension>
E/flutter (13899): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (13899): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
E/flutter (13899): #4      MediaInfo.getMediaInfo (package:media_info/media_info.dart:25:21)

**Comment by ened** [comment]
OK, I will research the problem. Sorry for the delay.

**Comment by dmcrobin** [comment]
Delay?? It's like a month!!!

**Comment by Tonigt** [comment]
> OK, I will research the problem. Sorry for the delay.

thanks, very much

**Comment by ened** [comment]
@Tonigt if you can share your video file as well?

@dmcrobin @Tonigt are the files you are referring to playable using the standard `video_player` package? This project is built on the same foundation.

**Comment by ened** [comment]
Please have a go with V0.6.2 which was just released & open a new ticket when needed.
